apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metabase.name }}-deployment
  namespace: maistodos
  annotations:
    autoscaling.knative.dev/metricName: cpu
    autoscaling.knative.dev/target: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: metabase
        image: "{{ .Values.metabase.image.repository }}:{{ .Values.metabase.image.tag }}"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/metabase
        ports:
        - containerPort: {{ .Values.metabase.service.port }}
          name: http
        envFrom:
        - configMapRef:
            name: metabase-config
        - secretRef:
            name: metabase-secrets
      volumes:
      - name: config-volume
        configMap:
          name: metabase-config
