apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.metabase.name }}-hpa
  namespace: {{ .Values.metabase.namespace }}
  labels:
    app: {{ .Values.metabase.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.metabase.name }}
  minReplicas: {{ .Values.metabase.hpa.minReplicas }}
  maxReplicas: {{ .Values.metabase.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.metabase.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.metabase.hpa.targetMemoryUtilizationPercentage }}