apiVersion: v1
kind: Secret
metadata:
  name: metabase-secrets
  namespace: maistodos
type: Opaque
data:
  MB_DB_USER: {{ .Values.metabase.db.user }}
  MB_DB_PASS: {{ .Values.metabase.db.password }}
