version: 2.1
executors:
  terraform:
    docker:
      - image: hashicorp/terraform:0.12.24
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
      TF_VAR_database_password: $METABASE_DATABASE_PASSWORD

jobs:
  plan:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Terraform Plan
          command: |
            export TF_VAR_database_password=$METABASE_DATABASE_PASSWORD
            terraform init
            terraform plan

  apply:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Terraform Apply
          command: |
            export TF_VAR_database_password=$METABASE_DATABASE_PASSWORD
            terraform init
            terraform apply -auto-approve

workflows:
  version: 2
  plan-approve-apply:
    jobs:
      - plan:
          context: 
            - aws-context
            - metabase-context
          filters:
            branches:
              only: main
      - approve:
          type: approval
          requires:
            - plan
      - apply:
          context: 
            - aws-context
            - metabase-context
          requires:
            - approve
          filters:
            branches:
              only: main