metabase:
  name: metabase
  namespace: maistodos
  image:
    repository: metabase/metabase
    tag: latest
  service:
    type: ClusterIP
    port: 3000
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  db:
    host: "seu-endpoint-do-rds"  # Substitua pelo endpoint real do seu RDS
    port: 5432  # Substitua pela porta correta do seu RDS
    name: "seu-nome-de-banco-de-dados"
    user: "seu-usuario-do-banco"
    password: "sua-senha-do-banco"
