metabase:
  name: metabase
  namespace: maistodos
  image:
    repository: metabase/metabase
    tag: latest
  service:
    type: ClusterIP
    port: 3000
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  db:
    host: ""
    port: 5432
    name: "" # Substitua pelo nome do seu banco de dados
    user: ""
    password: ""
